// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/alarm": {
            "get": {
                "description": "알람 현황을 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "알람 현황 가져오기",
                "parameters": [
                    {
                        "enum": [
                            "bos",
                            "pas",
                            "con",
                            "ias"
                        ],
                        "type": "string",
                        "description": "Origin Type",
                        "name": "originType",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "cpu",
                            "memory",
                            "disk"
                        ],
                        "type": "string",
                        "description": "Alarm Type",
                        "name": "alarmType",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "warning",
                            "critical"
                        ],
                        "type": "string",
                        "description": "Level",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Resolve Status",
                        "name": "resolveStatus",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.Alarms"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/alarm/action": {
            "get": {
                "description": "알람에 대한 조치 내용을 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "알람 조치 내용 가져오기",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Alarm ID",
                        "name": "alarmId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Alarm Action Desc",
                        "name": "alarmActionDesc",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            },
            "post": {
                "description": "알람에 대한 조치 내용을 신규 작성한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "알람 조치 내용 신규 작성하기",
                "parameters": [
                    {
                        "description": "신규 작성할 알람 정보를 주입한다.",
                        "name": "AlarmActions",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AlarmActions"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            },
            "delete": {
                "description": "알람에 대한 조치 내용을 삭제한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "알람에 대한 조치 내용 삭제하기",
                "parameters": [
                    {
                        "description": "삭제할 알람 정보(ID)를  주입한다.",
                        "name": "AlarmActionRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AlarmActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            },
            "patch": {
                "description": "알람에 대한 조치 내용을 수정한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "알람 조치 내용 수정하기",
                "parameters": [
                    {
                        "description": "수정할 알람 정보(ID)를  주입한다.",
                        "name": "AlarmActionRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AlarmActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            }
        },
        "/api/v1/alarm/policy": {
            "get": {
                "description": "전체 알람 정책을 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "전체 알람 정책 가져오기",
                "parameters": [
                    {
                        "enum": [
                            "bos",
                            "pas",
                            "con",
                            "ias"
                        ],
                        "type": "string",
                        "description": "Origin Type",
                        "name": "originType",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "cpu",
                            "memory",
                            "disk"
                        ],
                        "type": "string",
                        "description": "Alarm Type",
                        "name": "alarmType",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.AlarmPolicies"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "알람 정책을 업데이트 한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "알람 정책 업데이트하기",
                "parameters": [
                    {
                        "description": "알람 정책을 변경하기 위한 정보를 주입한다.",
                        "name": "AlarmPolicyRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.AlarmPolicyRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            },
            "post": {
                "description": "알람 정책을 생성한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "알람 정책 생성하기",
                "parameters": [
                    {
                        "description": "생성할 알람 정책 정보를 주입한다.",
                        "name": "AlarmPolicies",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.AlarmPolicies"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            }
        },
        "/api/v1/alarm/target": {
            "put": {
                "description": "알람 타겟을 업데이트 한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "알람 타겟 업데이트하기",
                "parameters": [
                    {
                        "description": "알람 타겟을 변경하기 위한 정보를 주입한다.",
                        "name": "AlarmTargetRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.AlarmTargetRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            }
        },
        "/api/v1/ap/alarm/sns": {
            "get": {
                "description": "알람 받는 SNS 계정 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "알람 받는 SNS 계정 가져오기",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.AlarmSns"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "알람 받을 SNS 계정 정보를 수정한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "알람 받을 SNS 계정 수정하기",
                "parameters": [
                    {
                        "description": "수정할 SNS 계정 정보를 주입한다.",
                        "name": "SnsAccountRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SnsAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            },
            "post": {
                "description": "알람 받을 SNS 계정을 등록한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "알람 받을 SNS 계정 등록하기",
                "parameters": [
                    {
                        "description": "알람 받을 SNS 계정 정보를 주입한다.",
                        "name": "SnsAccountRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SnsAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            },
            "delete": {
                "description": "알람 받는 SNS 계정을 삭제한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "알람 받는 SNS 계정 삭제하기",
                "parameters": [
                    {
                        "description": "삭제할 SNS 계정을 정보(ChannelId)를  주입한다.",
                        "name": "SnsAccountRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SnsAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            }
        },
        "/api/v1/ap/alarm/statistics/resource": {
            "get": {
                "description": "알람 통계 그래프(자원별)를 그리기 위한 데이터를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "알람 통계 그래프(자원별)를 그리기 위한 데이터 가져오기",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            }
        },
        "/api/v1/ap/alarm/statistics/total": {
            "get": {
                "description": "알람 통계 그래프를 그리기 위한 데이터를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "알람 통계 그래프를 그리기 위한 데이터 가져오기",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                        }
                    }
                }
            }
        },
        "/api/v1/ap/bosh/overview": {
            "get": {
                "description": "Bosh Overview 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Bosh Overview 정보를 가져온다.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.BoshOverview"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/bosh/process": {
            "get": {
                "description": "Bosh의 프로세스 목록을 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Bosh의 프로세스 목록을 가져온다.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bosh의 프로세스 목록 조회시 Bosh ID를 주입한다.",
                        "name": "uuid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.BoshProcess"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/bosh/summary": {
            "get": {
                "description": "Bosh Summary 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Bosh Summary 정보를 가져온다.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.BoshSummary"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/container/app": {
            "get": {
                "description": "현재 배포된 모든 App의 상세정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "App 정보 가져오기",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.AppInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/container/cell": {
            "get": {
                "description": "현재 배포된 모든 Diego-Cell VM의 상세정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Cell 정보 가져오기",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.CellInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/container/cell/status": {
            "get": {
                "description": "Diego-Cell VM의 Status 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Cell Status 정보 가져오기",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.Status"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/container/container": {
            "get": {
                "description": "현재 배포된 모든 App 당 생성된 Container 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Container 정보 가져오기",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.ContainerInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/container/container/cpu/{id}/loads": {
            "get": {
                "description": "Container CPU Loads 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Container CPU Loads 정보 가져오기",
                "parameters": [
                    {
                        "type": "string",
                        "example": "10.255.116.231-10.200.1.132",
                        "description": "Container ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "15m",
                        "description": "Default Time Range",
                        "name": "defaultTimeRange",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1m",
                        "description": "Group By",
                        "name": "groupBy",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/ap/container/container/cpu/{id}/usages": {
            "get": {
                "description": "Container CPU Usages 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Container CPU Usages 정보 가져오기",
                "parameters": [
                    {
                        "type": "string",
                        "example": "10.255.116.231-10.200.1.132",
                        "description": "Container ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "15m",
                        "description": "Default Time Range",
                        "name": "defaultTimeRange",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1m",
                        "description": "Group By",
                        "name": "groupBy",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/ap/container/container/disk/{id}/usages": {
            "get": {
                "description": "Container Disk Usages 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Container Disk Usages 정보 가져오기",
                "parameters": [
                    {
                        "type": "string",
                        "example": "10.255.116.231-10.200.1.132",
                        "description": "Container ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "15m",
                        "description": "Default Time Range",
                        "name": "defaultTimeRange",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1m",
                        "description": "Group By",
                        "name": "groupBy",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/ap/container/container/memory/{id}/usages": {
            "get": {
                "description": "Container Memory Usages 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Container Memory Usages 정보 가져오기",
                "parameters": [
                    {
                        "type": "string",
                        "example": "10.255.116.231-10.200.1.132",
                        "description": "Container ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "15m",
                        "description": "Default Time Range",
                        "name": "defaultTimeRange",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1m",
                        "description": "Group By",
                        "name": "groupBy",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/ap/container/container/network/{id}/bytes": {
            "get": {
                "description": "Container Network Bytes 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Container Network Bytes 정보 가져오기",
                "parameters": [
                    {
                        "type": "string",
                        "example": "10.255.116.231-10.200.1.132",
                        "description": "Container ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "15m",
                        "description": "Default Time Range",
                        "name": "defaultTimeRange",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1m",
                        "description": "Group By",
                        "name": "groupBy",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/ap/container/container/network/{id}/drops": {
            "get": {
                "description": "Container Network Drops 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Container Network Drops 정보 가져오기",
                "parameters": [
                    {
                        "type": "string",
                        "example": "10.255.116.231-10.200.1.132",
                        "description": "Container ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "15m",
                        "description": "Default Time Range",
                        "name": "defaultTimeRange",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1m",
                        "description": "Group By",
                        "name": "groupBy",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/ap/container/container/network/{id}/errors": {
            "get": {
                "description": "Container Network Errors 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Container Network Errors 정보 가져오기",
                "parameters": [
                    {
                        "type": "string",
                        "example": "10.255.116.231-10.200.1.132",
                        "description": "Container ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "15m",
                        "description": "Default Time Range",
                        "name": "defaultTimeRange",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1m",
                        "description": "Group By",
                        "name": "groupBy",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/ap/container/container/status": {
            "get": {
                "description": "Container의 Status 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Container Status 정보 가져오기",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.Status"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/container/overview": {
            "get": {
                "description": "Container 페이지를 위한 Overview 정보를 가져온다.\nZone - Cell - App - Container 구조를 매핑하여 보여준다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Container 페이지 Overview 정보 가져오기",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.Overview"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/container/zone": {
            "get": {
                "description": "Zone 기준 현재 배포된 Diego-Cell VM 갯수를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Zone 정보 가져오기",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.ZoneInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/paasta/overview": {
            "get": {
                "description": "PaaS-TA Overview 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "PaaS-TA Overview 정보를 가져온다.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.PaastaOverview"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/paasta/process": {
            "get": {
                "description": "PaaS-TA Core 별 프로세스 목록을 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "PaaS-TA Core 별 프로세스 목록을 가져온다.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Paasta의 프로세스 목록 조회시 VM ID를 주입한다.",
                        "name": "uuid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.PaastaProcess"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ap/paasta/summary": {
            "get": {
                "description": "PaaS-TA Summary 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "PaaS-TA Summary 정보를 가져온다.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.PaastaSummary"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/bosh": {
            "get": {
                "description": "Bosh의 목록을 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Bosh의 목록을 가져온다.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.Bosh"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/bosh/Chart": {
            "get": {
                "description": "Bosh의 차트 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "Bosh의 차트 정보를 가져온다.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bosh의 차트 정보 조회시 Bosh ID를 주입한다.",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.BoshChart"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/log": {
            "get": {
                "description": "로그 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "로그 정보 가져오기",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PaaS-TA Core 별 로그 정보 조회시 VM UUID를 주입한다.",
                        "name": "uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PaaS-TA Core 별 로그 정보 조회시 키워드 (keyword)를      주입한다.",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PaaS-TA Core 별 로그 정보 조회시 대상날짜 (targetDate)를  주입한다.",
                        "name": "targetDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PaaS-TA Core 별 로그 정보 조회시 시작시간 (startTime)를   주입한다.",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PaaS-TA Core 별 로그 정보 조회시 종료시간 (endTime)를     주입한다.",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PaaS-TA Core 별 로그 정보 조회시 조회기간 (period)를      주입한다.",
                        "name": "period",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.Logs"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/paasta": {
            "get": {
                "description": "PaaS-TA Core의 목록을 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "PaaS-TA Core의 목록을 가져온다.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.Paasta"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/paasta/Chart": {
            "get": {
                "description": "PaaS-TA Core 별 차트 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AP"
                ],
                "summary": "PaaS-TA Core 별 차트 정보를 가져온다.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PaaS-TA Core 별 차트 정보 조회시 VM UUID를 주입한다.",
                        "name": "uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PaaS-TA Core 별 차트 정보 조회시 기본 시간 범위 (defaultTimeRange=15m)를               주입한다.",
                        "name": "defaultTimeRange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PaaS-TA Core 별 차트 정보 조회시 시간 범위 시작 (timeRangeFrom=2022-06-16T10:21:39)를  주입한다.",
                        "name": "timeRangeFrom",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PaaS-TA Core 별 차트 정보 조회시 시간 범위 종료 (timeRangeTo=2022-06-16T10:21:39)를    주입한다.",
                        "name": "timeRangeTo",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PaaS-TA Core 별 차트 정보 조회시 그룹 (groupBy=1m)을                               주입한다.",
                        "name": "groupBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.PaastaChart"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/token": {
            "put": {
                "description": "토큰 정보를 리프레시한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "토큰 리프레시하기",
                "parameters": [
                    {
                        "description": "토큰을 리프레시하기 위한 토큰 정보를 제공한다.",
                        "name": "TokenDetails",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RefreshToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.TokenDetails"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "토큰 정보를 생성한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "토큰 생성하기",
                "parameters": [
                    {
                        "description": "토큰을 생성하기 위해 필요한 유저 정보를 제공한다.",
                        "name": "UserInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.TokenDetails"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "description": "전체 또는 단일 유저 정보를 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "전체 또는 단일 유저 정보 가져오기",
                "parameters": [
                    {
                        "type": "string",
                        "description": "단일 사용자 정보 조회시 유저명을 주입한다.",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiHelpers.BasicResponseForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseInfo": {
                                            "$ref": "#/definitions/v1.UserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apiHelpers.BasicResponseForm": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "responseInfo": {},
                "responseTime": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                },
                "statusText": {
                    "type": "string"
                }
            }
        },
        "gogobosh.Client": {
            "type": "object",
            "properties": {
                "endpoint": {
                    "$ref": "#/definitions/gogobosh.Endpoint"
                }
            }
        },
        "gogobosh.Endpoint": {
            "type": "object",
            "properties": {
                "doppler_logging_endpoint": {
                    "type": "string"
                }
            }
        },
        "v1.AlarmActionRequest": {
            "type": "object",
            "properties": {
                "alarmActionDesc": {
                    "type": "string",
                    "example": "Modify From Swagger Web"
                },
                "alarmId": {
                    "type": "integer",
                    "example": 115
                },
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "v1.AlarmActions": {
            "type": "object",
            "properties": {
                "alarmActionDesc": {
                    "type": "string",
                    "example": "Creat From Swagger Web"
                },
                "alarmId": {
                    "type": "integer",
                    "example": 115
                }
            }
        },
        "v1.AlarmPolicies": {
            "type": "object",
            "properties": {
                "alarmType": {
                    "type": "string",
                    "example": "cpu"
                },
                "comment": {
                    "type": "string",
                    "example": "Init From Swagger Web"
                },
                "criticalThreshold": {
                    "type": "integer",
                    "example": 99
                },
                "id": {
                    "type": "integer"
                },
                "measureTime": {
                    "type": "integer",
                    "example": 600
                },
                "originType": {
                    "type": "string",
                    "example": "bos"
                },
                "repeatTime": {
                    "type": "integer",
                    "example": 10
                },
                "warningThreshold": {
                    "type": "integer",
                    "example": 88
                }
            }
        },
        "v1.AlarmPolicyRequest": {
            "type": "object",
            "required": [
                "originType"
            ],
            "properties": {
                "alarmType": {
                    "type": "string",
                    "example": "cpu"
                },
                "criticalThreshold": {
                    "type": "integer",
                    "example": 89
                },
                "measureTime": {
                    "type": "integer",
                    "example": 600
                },
                "originType": {
                    "type": "string",
                    "example": "bos"
                },
                "repeatTime": {
                    "type": "integer",
                    "example": 10
                },
                "warningThreshold": {
                    "type": "integer",
                    "example": 88
                }
            }
        },
        "v1.AlarmSns": {
            "type": "object",
            "properties": {
                "channelId": {
                    "type": "integer"
                },
                "expl": {
                    "type": "string"
                },
                "modiDate": {
                    "type": "string"
                },
                "modiUser": {
                    "type": "string"
                },
                "originType": {
                    "type": "string"
                },
                "regDate": {
                    "type": "string"
                },
                "regUser": {
                    "type": "string"
                },
                "snsId": {
                    "type": "string"
                },
                "snsSendYN": {
                    "type": "string"
                },
                "snsType": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "v1.AlarmTargetRequest": {
            "type": "object",
            "required": [
                "originType"
            ],
            "properties": {
                "mailAddress": {
                    "type": "string",
                    "example": "paasta-admin@paasta.org"
                },
                "mailSendYN": {
                    "type": "string",
                    "example": "N"
                },
                "originType": {
                    "type": "string",
                    "example": "bos"
                }
            }
        },
        "v1.Alarms": {
            "type": "object",
            "properties": {
                "alarmCnt": {
                    "type": "integer"
                },
                "alarmMessage": {
                    "type": "string"
                },
                "alarmTitle": {
                    "type": "string"
                },
                "alarmType": {
                    "type": "string"
                },
                "appIndex": {
                    "type": "integer"
                },
                "appName": {
                    "type": "string"
                },
                "appYN": {
                    "type": "string"
                },
                "completeDate": {
                    "type": "string"
                },
                "completeUser": {
                    "type": "string"
                },
                "containerName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "modiDate": {
                    "type": "string"
                },
                "modiUser": {
                    "type": "string"
                },
                "originId": {
                    "type": "integer"
                },
                "originType": {
                    "type": "string"
                },
                "regDate": {
                    "type": "string"
                },
                "regUser": {
                    "type": "string"
                },
                "resolveStatus": {
                    "type": "string"
                }
            }
        },
        "v1.AppInfo": {
            "type": "object",
            "properties": {
                "appName": {
                    "type": "string"
                },
                "buildpack": {
                    "type": "string"
                },
                "cellName": {
                    "type": "string"
                },
                "cfApi": {
                    "type": "string"
                },
                "containerInfo": {
                    "$ref": "#/definitions/v1.ContainerInfo"
                },
                "createdAt": {
                    "type": "string"
                },
                "diskQuota": {
                    "type": "integer"
                },
                "instances": {
                    "type": "integer"
                },
                "memory": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "v1.Bosh": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "client": {
                    "$ref": "#/definitions/gogobosh.Client"
                },
                "deployment": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "v1.BoshChart": {
            "type": "object",
            "properties": {
                "defaulttimerange": {
                    "type": "string"
                },
                "groupby": {
                    "type": "string"
                },
                "isconvertkb": {
                    "type": "boolean"
                },
                "metricData": {
                    "type": "object",
                    "additionalProperties": true
                },
                "metricname": {
                    "type": "string"
                },
                "sqlquery": {
                    "type": "string"
                },
                "timerangefrom": {
                    "type": "string"
                },
                "timerangeto": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "v1.BoshOverview": {
            "type": "object",
            "properties": {
                "critical": {
                    "type": "string"
                },
                "failed": {
                    "type": "string"
                },
                "running": {
                    "type": "string"
                },
                "total": {
                    "type": "string"
                },
                "warning": {
                    "type": "string"
                }
            }
        },
        "v1.BoshProcess": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "string"
                },
                "memory": {
                    "type": "number"
                },
                "pid": {
                    "type": "string"
                },
                "process": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "v1.BoshSummary": {
            "type": "object",
            "properties": {
                "boshSummaryMetric": {
                    "$ref": "#/definitions/v1.BoshSummaryMetric"
                },
                "ip": {
                    "type": "string"
                },
                "metricName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sqlQuery": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "v1.BoshSummaryMetric": {
            "type": "object",
            "properties": {
                "core": {
                    "type": "string"
                },
                "cpuErrStat": {
                    "type": "string"
                },
                "cpuUsage": {
                    "type": "number"
                },
                "dataDisk": {
                    "type": "number"
                },
                "diskDataErrStat": {
                    "type": "string"
                },
                "diskRootErrStat": {
                    "type": "string"
                },
                "diskStatus": {
                    "type": "string"
                },
                "memErrStat": {
                    "type": "string"
                },
                "memoryUsage": {
                    "type": "number"
                },
                "state": {
                    "type": "string"
                },
                "totalDisk": {
                    "type": "number"
                },
                "totalMemory": {
                    "type": "number"
                }
            }
        },
        "v1.CellInfo": {
            "type": "object",
            "properties": {
                "appCnt": {
                    "type": "integer"
                },
                "appInfo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.AppInfo"
                    }
                },
                "cellId": {
                    "type": "integer"
                },
                "cellIp": {
                    "type": "string"
                },
                "cellName": {
                    "type": "string"
                },
                "containerCnt": {
                    "type": "integer"
                },
                "zoneName": {
                    "type": "string"
                }
            }
        },
        "v1.Container": {
            "type": "object",
            "properties": {
                "appIndex": {
                    "type": "string"
                },
                "containerId": {
                    "type": "string"
                }
            }
        },
        "v1.ContainerInfo": {
            "type": "object",
            "properties": {
                "appName": {
                    "type": "string"
                },
                "container": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Container"
                    }
                }
            }
        },
        "v1.CreateToken": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "username": {
                    "type": "string",
                    "example": "username"
                }
            }
        },
        "v1.Logs": {
            "type": "object",
            "properties": {
                "endTime": {
                    "type": "string"
                },
                "keyword": {
                    "type": "string"
                },
                "logType": {
                    "type": "string"
                },
                "messages": {},
                "period": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "targetDate": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "v1.Overview": {
            "type": "object",
            "properties": {
                "zoneInfo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ZoneInfo"
                    }
                }
            }
        },
        "v1.Paasta": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "modiDate": {
                    "type": "string"
                },
                "modiUser": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "regDate": {
                    "type": "string"
                },
                "regUser": {
                    "type": "string"
                },
                "vmType": {
                    "type": "string"
                },
                "zoneId": {
                    "type": "integer"
                }
            }
        },
        "v1.PaastaChart": {
            "type": "object",
            "properties": {
                "defaulttimerange": {
                    "type": "string"
                },
                "groupby": {
                    "type": "string"
                },
                "isLikeQuery": {
                    "type": "boolean"
                },
                "isNonNegativeDerivative": {
                    "type": "boolean"
                },
                "isRespondKb": {
                    "type": "boolean"
                },
                "isconvertkb": {
                    "type": "boolean"
                },
                "metricData": {
                    "type": "object",
                    "additionalProperties": true
                },
                "metricname": {
                    "type": "string"
                },
                "sqlquery": {
                    "type": "string"
                },
                "timerangefrom": {
                    "type": "string"
                },
                "timerangeto": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "v1.PaastaOverview": {
            "type": "object",
            "properties": {
                "critical": {
                    "type": "string"
                },
                "failed": {
                    "type": "string"
                },
                "running": {
                    "type": "string"
                },
                "total": {
                    "type": "string"
                },
                "warning": {
                    "type": "string"
                }
            }
        },
        "v1.PaastaProcess": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer"
                },
                "memory": {
                    "type": "integer"
                },
                "pid": {
                    "type": "string"
                },
                "process": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "v1.PaastaSummary": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "paastaSummaryMetric": {
                    "$ref": "#/definitions/v1.PaastaSummaryMetric"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "v1.PaastaSummaryMetric": {
            "type": "object",
            "properties": {
                "core": {
                    "type": "string"
                },
                "cpuErrStat": {
                    "type": "string"
                },
                "cpuUsage": {
                    "type": "number"
                },
                "dataDisk": {
                    "type": "integer"
                },
                "diskDataErrStat": {
                    "type": "string"
                },
                "diskRootErrStat": {
                    "type": "string"
                },
                "diskStatus": {
                    "type": "string"
                },
                "memErrStat": {
                    "type": "string"
                },
                "memoryUsage": {
                    "type": "number"
                },
                "state": {
                    "type": "string"
                },
                "totalDisk": {
                    "type": "integer"
                },
                "totalMemory": {
                    "type": "integer"
                }
            }
        },
        "v1.RefreshToken": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string",
                    "example": "refreshToken"
                }
            }
        },
        "v1.SnsAccountRequest": {
            "type": "object",
            "properties": {
                "expl": {
                    "type": "string"
                },
                "originType": {
                    "type": "string"
                },
                "snsId": {
                    "type": "string"
                },
                "snsSendYN": {
                    "type": "string"
                },
                "snsType": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "v1.Status": {
            "type": "object",
            "properties": {
                "critical": {
                    "type": "integer"
                },
                "failed": {
                    "type": "integer"
                },
                "running": {
                    "type": "integer"
                },
                "warning": {
                    "type": "integer"
                }
            }
        },
        "v1.TokenDetails": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "accessUuid": {
                    "type": "string"
                },
                "atExpires": {
                    "type": "integer"
                },
                "refreshToken": {
                    "type": "string"
                },
                "refreshUuid": {
                    "type": "string"
                },
                "rtExpires": {
                    "type": "integer"
                }
            }
        },
        "v1.UserInfo": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "authC1": {
                    "type": "string"
                },
                "authC2": {
                    "type": "string"
                },
                "authI1": {
                    "type": "string"
                },
                "authI2": {
                    "type": "string"
                },
                "authP1": {
                    "type": "string"
                },
                "authP2": {
                    "type": "string"
                },
                "caasToken": {
                    "type": "string"
                },
                "caasUserId": {
                    "type": "string"
                },
                "caasUserPw": {
                    "type": "string"
                },
                "caasUserUseYn": {
                    "type": "string"
                },
                "iaasToken": {
                    "type": "string"
                },
                "iaasUserId": {
                    "type": "string"
                },
                "iaasUserPw": {
                    "type": "string"
                },
                "iaasUserUseYn": {
                    "type": "string"
                },
                "paasAdminYn": {
                    "type": "string"
                },
                "paasToken": {
                    "type": "string"
                },
                "paasUserId": {
                    "type": "string"
                },
                "paasUserPw": {
                    "type": "string"
                },
                "paasUserUseYn": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "sysType": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "userAuth": {
                    "type": "string"
                },
                "userEmail": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "userNm": {
                    "type": "string"
                },
                "userPw": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.ZoneInfo": {
            "type": "object",
            "properties": {
                "cellCnt": {
                    "type": "integer"
                },
                "cellInfo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.CellInfo"
                    }
                },
                "zoneName": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Common Module API (Alarm \u0026 Log)",
            "name": "Common"
        },
        {
            "description": "Application Platform API (Based on Cloud Foundry)",
            "name": "AP"
        },
        {
            "description": "Container Platform API (Based on Kubernetes)",
            "name": "CP"
        },
        {
            "description": "Application Performance Monitoring API (Based on Pinpoint)",
            "name": "SaaS"
        },
        {
            "description": "Infrastructure Monitoring API (Based on Openstack/Zabbix)",
            "name": "IaaS"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "5.8.0",
	Host:             "localhost:8395",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Monitoring Dashboard API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
