apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gs-spring-boot-docker-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: gs-spring-boot-docker-deployment
  targetCPUUtilizationPercentage: 50

